services:
  mongo:
    image: mongo:5.0.26  
    container_name: mongo
    command: mongod --quiet --dbpath /data/db --replSet rs --port 27017 --bind_ip 0.0.0.0
    volumes:
      - mongo_volume:/data/db
    ports:
      - "27017:27017"

  orion-ld:
    image: fiware/orion-ld:latest
    platform: linux/amd64
    container_name: orion-ld
    depends_on:
      - mongo
    environment:
      - ORIONLD_MONGO_HOST=mongo
      - ORIONLD_MONGO_PORT=27017
      - ORIONLD_LOG_LEVEL=INFO
    command: >
      -dbhost mongo
      -logLevel DEBUG
    ports:
      - "1026:1026"

volumes:
  mongo_volume:
