#!
name: OpenSSF Scorecard Analysis
on:
  schedule:
    # Saturdays at 02:15 UTC
    - cron: "15 2 * * 6"
    # Wednesdays at 02:15 UTC
    - cron: "15 2 * * 3"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  scorecard-analysis:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186 # v2.4.1
    with:
      publish-results: false
